// Generates server/migrations/0002_seed_users.sql from
// creator2-profiles-export.json. Re-run this if the roster export changes;
// the output is meant to be committed, not generated at deploy time.
//
// Only email / display_name / role are carried over -- creator2's
// per-app permissions JSON (boq/procurement/etc.) doesn't apply to
// Switchboard, which uses its own app_access table instead (see
// ../migrations/0001_init.sql). creator2's 'admin' role becomes
// Switchboard's 'admin' too (same people administering both seems the
// reasonable default); creator2's 'manager' tier has no Switchboard
// equivalent and becomes plain 'user' -- Switchboard's admin panel is the
// place to promote anyone further, per person, if that turns out wrong.

const fs = require('fs');
const path = require('path');

const source = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'creator2-profiles-export.json'), 'utf8')
);

function sqlString(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}

const rows = source.map((row) => {
  const role = row.role === 'admin' ? 'admin' : 'user';
  return `  (${sqlString(row.email)}, ${sqlString(row.display_name)}, ${sqlString(role)})`;
});

const sql = `-- Generated by server/seed/generate-seed.js from
-- creator2-profiles-export.json. Do not hand-edit -- change the source
-- JSON and re-run the script instead.
--
-- Safe to re-run: existing rows are left untouched (ON CONFLICT DO NOTHING),
-- so this only ever adds people, never overwrites an admin's later changes
-- to someone's role.

insert into switchboard_users (email, display_name, role)
values
${rows.join(',\n')}
on conflict (email) do nothing;
`;

const outPath = path.join(__dirname, '..', 'migrations', '0002_seed_users.sql');
fs.writeFileSync(outPath, sql);
console.log(`Wrote ${rows.length} users to ${outPath}`);
